apiVersion: v1
kind: Service
metadata:
  name: lsc-service
spec:
  selector:
    app: lsc-http-server
  ports:
    - protocol: TCP
      port: 80            
      targetPort: 80      
  type: LoadBalancer     
